### PR TITLE
Customer History, Account Management,  Clean Up and Better File Structure

### LINKED ISSUE #75: User story #5 : Customer and seller managing their profile
As a customer/seller, I want to be able to manage my profile because I would like to update certain credentials, if needed, to make my account more secure.

Tasks
- Portal for users to modify their accounts details
- Backend functionality that will modify the accounts details
- Order history for customers

Tasks references : #98 

Acceptance tests:

Positive case 1
1. The customer or the seller clicks the ‘Manage my profile’.
2. The list of information of the customer or the seller appears with buttons ’Edit’ and ‘Change password’.
3. The customer or the seller inputs new email. 
4. The customer or the seller clicks on ‘Edit’ button.
5. The new email or new username is saved in the database.
6. The customer or the seller clicks ‘Logout’ button.
7. The customer or the seller clicks ‘Login’ button.
8. Login form appears.
9. The customer or the seller inputs new email and unchanged password.
10. The customer or the seller logins successfully.

Positive case 2
1. The customer or the seller clicks the ‘Manage my profile’.
2. The list of information of the customer or the seller appears with buttons ’Edit’ and ‘Change password’.
3. The customer or the seller clicks on ‘Change password’ button.
4. The customer or the seller inputs new password.
5. The customer or the seller clicks on ‘Change password’ button.
7. The new password is saved in the database.
7. The customer or the seller clicks ‘Logout’ button.
8. The customer or the seller clicks ‘Login’ button.
9. Login form appears.
10. The customer or the seller inputs new password with unchanged email.
11. The customer or the seller logins successfully.

Negative case 1
1. The customer or the seller clicks the ‘Manage my profile’.
2. The list of information of the customer or the seller appears with buttons ’Edit’ and ‘Change password’.
3. The customer or the seller inputs new email.
4. The customer or the seller clicks on ‘Edit’ button.
5. The new email is not saved in the database.
6. The customer or the seller clicks ‘Logout’ button.
7. The customer or the seller clicks ‘Login’ button.
8. Login form appears.
9. The customer or the seller inputs new email and unchanged password.
10. The customer or the seller cannot login.

Negative case 2
1. The customer or the seller clicks the ‘Manage my profile’.
2. The list of information of the customer or the seller appears with buttons ’Edit’ and ‘Change password’.
3. The customer or the seller clicks on ‘Change password’ button.
4. The customer or the seller inputs new password.
5. The customer or the seller clicks on ‘Change password’ button.
6. The new password is not saved in the database.
7. The customer or the seller clicks ‘Logout’ button.
8. The customer or the seller clicks ‘Login’ button.
9. Login form appears.
10. The customer or the seller inputs new password with unchanged email.
11. The customer or the seller cannot login.

### LINKED ISSUE #80: User Order History
Add a history of orders

### LINKED ISSUE #83: User story#3 : Story points
Story points : 7

A story point of 7 was given to this user story since there isn't more features that are being added to this user story compared to user story 2. Both user story 2 and user story 3 are similar in terms of the implementation of the code. The admin is only able to manage profiles where as the seller is able to manage products. Both are doing the same thing essentially but with different database objects. In this user story the admin should be able to add/edit/remove accounts, which is all features that the seller is able to do with their products. In general, user story 3 was given a story point of 7, because of the possibility of reuse of code

### LINKED ISSUE #85: User Story #4 : Story points
Story points: 6

A story point of 6 was given to this user story since compared to other stories, less functionalities needs to be implemented in this user story. The tasks are significantly less than other user stories. The cart contributes to the majority of the story points of this user story since the front end and back end functionalities can be very complex as the cart is not a feature that the members of our team are familiar to code. It is something new to our members.

### LINKED ISSUE #86: User Story #4: Risk
Risk: High

The customer should be able to apply filters for products to make their search more easier. A possible risks to take into account is that filters may not produce the exact results that customer expected. If the products do not match the inputs that were given by the user in the filter, this will dissatisfy the customers. A counter measure would be to do regular test of this functionality with different combinations of inputs and check if the results match the inputs given. The customer should also be able buy the items once they have been searched and should be able to process the order using the cart. The possible risk to take into account is that customer may have their order history be leaked and visible by others.  A counter measure would be to ensure that the database is secure and that no one is able to access the order history except for the user

Priority: High

### LINKED ISSUE #98: Page and functionality for customer/seller to modify account
A Page that would allow users to modify accounts details

### LINKED ISSUE #99: User story 5: Story points
Story point : 6

A user story point of 6 has been given since the tasks to be completed for this user story are significantly less than other users stories. Only 2 tasks needs to be completed for this user story and one of them is not a very complex feature since it has been partly implemented in previous user story (managing profile). The order history feature takes up most this story point as it a new feature to be implemented.

### LINKED ISSUE #100: User story 5 : Risk
Risk : High

The user should be able to edit accounts details. The risk to to take into consideration in this user story is that the accounts details can be leaked and can be accessed by someone else. A counter measure, would be to have the manage profile page very secure and encrypt any information that are personal

Priority : Medium

### PR DESCRIPTION
**Pull request by MichaelDjabauri**
This PR adds the following
#98 Give customers and sellers the ability to modify their accounts
   -email, name, password

#80 Implement user history showing previously bought items.

Fix bug where cart items would disappear.

Clean up code and file structure for a better and cleaner architecture.

### CODE REVIEW

**Comment by imran1289-ah** [comment]
THIS IS FREAKING AWSOME !! nice work altough can u add some little stuff that would make it a bit better
- In the cart, would u be able to output the total price of the cart products ?
- Also in the order history, i think u can get the date of the history using the react get current date function https://reactgo.com/react-get-current-date/,  that would be a cool feature to add, but is up to you 

Im gonna request changes, but if u don't have time you really don't need to do these additional changes, I will just approve it and merge it

**Review by imran1289-ah — CHANGES_REQUESTED** [review]
As mentioned in my previous comment

**Comment by MichaelDjabauri** [comment]
Those features would be nice additions to the project but dealing with the current timeframe I believe that this pr is sufficient in and of itself. You can merge the changes. 😁

**Comment by imran1289-ah** [comment]
ok no problem i will approve it

**Review by imran1289-ah — APPROVED** [review]
Approved !

**Pull request merged**
